<?php


class Cat extends Animal
{
    protected $homeOrStreetAnimal;

    public function __construct($name, $age, $homeOrStreetAnimal)
    {
        parent::__construct($name, $age);
        $this->homeOrStreetAnimal = $homeOrStreetAnimal;
    }

    public function getHomeOrStreetAnimal()
    {
        return $this->homeOrStreetAnimal;
    }

    public function setHomeOrStreetAnimal($homeOrStreetAnimal)
    {
        $this->homeOrStreetAnimal = $homeOrStreetAnimal;
    }


    public function getFood()
    {
        return 'If' . ' ' . $this->name . ' ' . 'see mouse, she want catch and eat.';
    }


    public function getActions()
    {
        return $this->name . ' ' . 'like sleep on the warm blanket.';
    }

    public function getBreath()
    {
        return parent::getBreath(); // TODO: Change the autogenerated stub
    }

}